spring:
  application:
    name: userservice
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness-tracker-user
    username: postgres
    password: Handa@898989

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081